name: 06 -activity-types
on: 
    pull_request:
        branches:
            - main
        types: [opened, synchronize]
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: mensaje
              run: echo "Running whenever a PR is opened or synchronized AND base branch is develop"
